In [31]:
import copy

class nbp_v:

    # checks if inputted list/matrix (list of lists) is of:
    # correct type
    # correct structure
    
    # variables stored:
    # vector is a list of the vector elements
    # direction is for the user to specify if the vector is horizontal or vertical (h or v)
    def __init__(self, vector, direction = "h"):
        
        if type(vector) != list:
            raise ValueError('The vector-input has to be list')
           
        for e in vector:
            if not (type(e) == int or type(e) == float):
                raise ValueError("All the vector elements must be of type int or float")  
        
        self.dimensions = len(vector)
        self.vector = vector
        self.direction = direction
        self.norm = sum([i**2 for i in self.vector]) ** 0.5
        
        
    def __add__(self, other):
        if not (isinstance(other, nbp_v)):
            raise ValueError("other must be of instance vector (nbp_v).")        
        
        if (len(self.vector)!= len(other.vector)):
            raise ValueError('The vectors are not of the same dimension.')        
        v1 = self.vector
        v2 = other.vector
        out = []
        for i in range(len(v1)):
            out.append(v1[i] + v2[i])
        return nbp_v(out)
    
    def __sub__(self, other):
        if not (isinstance(other, nbp_v)):
            raise ValueError("other must be of instance vector (nbp_v).")        
   
        if (len(self.vector)!= len(other.vector)):
            raise ValueError('vectors are not of the same dimension.')        
        v1 = self.vector
        v2 = other.vector
        out = []
        for i in range(len(v1)):
            out.append(v1[i] - v2[i])
        return nbp_v(out)  

    
    def sum_vec(self, lst):
        for vec in lst:
            if not (isinstance(vec, nbp_v)):
                raise ValueError("All of the other input have to be vectors (instance of nbp_v).")
        
        dimensions = [i.dimensions for i in lst]
        dimensions.append(self.dimensions)
        lst.append(self)
        if [dimensions[0]]*len(dimensions) != dimensions:
            raise ValueError('Some of the vectors have different dimensions.')
            
        out = []
        for i in range(dimensions[0]):
            out.append(sum([k.vector[i] for k in lst]))
                       
        return nbp_v(out)

######## printing functions ######
    
    # Printing the vector as a list.
    def __str__(self):
        return str(self.vector)    
    

    def nice(self):
        
        #The import statement is defined in the function due to reusability purposes
        #Furthermore, nice is a function purley for the user to have a nice display, and is therefore optional.
        #Having the import inside the function avoids importing a package that might not be used
        
        from IPython.display import display, Latex
        

        vector_line = [round(num, 3) for num in self.vector] # rounding so that the outcome is of normal size

        # Coding the applicable string,
        # using {} to control the formatting,
        # and using latex to display the vector
        text = ''
        if(self.direction == "h"):
            text += '&'.join(['{}' for i in range(len(self.vector))])

        else:
            for i in range(len(self.vector)):
                text += '{}\\\\'
                
        gen = '$\\begin{{bmatrix}} '+text+' \end{{bmatrix}}$'
        gen_f = gen.format(*vector_line) #matrix_line


        # printing
        display(Latex(f'{gen_f}'))

 

    ### checking if two vectors are orthogonal ###

    def orthogonal(self, other):
        return self.dot_product(other) == 0
       


#### manipulating vectors #######        

        
    def scalar(self, scalar):
        if (type(scalar) != int and type(scalar) != float):
            raise ValueError('The scalar parsed must be numerical.')        
        return nbp_v([i*scalar for i in self.vector], self.direction)
    
    def div_vec(self, divisor):
        if (type(divisor) != int and type(divisor) != float):
            raise ValueError('The divisor parsed must be numerical.') 
        return nbp_v([i/divisor for i in self.vector], self.direction)
    
    
    def linear_independent(self, other):
        if(self.direction!= other.direction or self.dimensions != other.dimensions):
            return True
        lst =[]
        if(self.direction == "h"):
            lst.append(self.vector)
            lst.append(other.vector)
        else:
            for i in range(len(self.vector)):
                lst2 = []
                lst2.append(self.vector[i])
                lst2.append(other.vector[i])
                lst.append(lst2)
        return nbp_m(lst).rank() >1
    
    def dot_product(self, other):
        if not (isinstance(other, nbp_v)):
            raise ValueError("other has to be of instance nbp_v.")
        if (self.dimensions != other.dimensions):
            raise ValueError('Multiplication cannot be done due to different dimensions.')
        return sum([self.vector[i]*other.vector[i] for i in range(len(self.vector))])
    
    
    def outer_product(self, other):
        if not (isinstance(other, nbp_v)):
            raise ValueError("other has to be of instance nbp_v")
        if (self.dimensions != other.dimensions):
            raise ValueError('The outer product cannot be done due to different dimensions.')
        if (self.direction == other.direction):
            raise ValueError("The vectors must have different directions to compute the outer product.")
            
        # The outer product of the first vector (m x n), and the second vector (n x j) result in the matrix: m x j
    
        d1 = len(self.vector)
        d2 = len(other.vector)
    
        # The function returns an instance of nbp_m.
        res = nbp_m([0 for i in range(d1*d2)], d1)
    
        for i in range(d1):
            for j in range(d2):
                res.matrix[i][j] = self.vector[i]*other.vector[j]
                
        return res
    
    

class nbp_m:
    
    # __init__ function checks if the inputted list/ matrix (list of lists) is of:
    # correct type
    # correct structure

    def __init__(self, matrix, rows = None):
        
        #list of types for input
        types = [type(element) for element in matrix]
        
        # matrix has to be a list
        if type(matrix) != list:
            raise ValueError('The matrix has to be a list:\n1 - list of lists.\n2 - list of elements with rows stated.')
            
        # if matrix given as list
        elif sum([t == list for t in types]) == 0:
            
            # only numerical values
            for e in matrix:
                if (type(e) != int and type(e) != float):
                    raise ValueError('The given list contains values that are not numerical.')
            
            # rows have to be stated
            if rows == None:
                raise ValueError('The number of rows have to be stated.')
                
            # number of rows has to be an integer bigger than 1
            elif (type(rows) != int) or rows < 2:
                raise ValueError('The number of rows has to be a numerical value that is bigger then 1.')
                
            # at least 4 elements to be considered a matrix
            elif len(matrix) < 4:
                raise ValueError('The matrix has to contain at least 4 elements.')
                
            # number of elements has to be a multiple of number of rows
            elif len(matrix) % rows != 0 :
                raise ValueError('''The number of elements in the given list has to be a multiple of the number of rows.\n
                Number of elements - {}\n
                Number of rows - {}'''.format(len(matrix), rows))
            
            # if nothing from above - then we can store the instance as matrix
            else:
                num = len(matrix)//rows
                m = [matrix[x:x+num] for x in range(0, len(matrix), num)]
                
                self.matrix = m
                self.rows = rows
                self.columns = len(m[0])

                    
        elif sum([t == list for t in types]) in  range(1,len(matrix)):
            raise ValueError('Both lists and non-lists in given list.')
        
        # if matrix given as a matrix - that is list of lists
        else:
            
            # if the matrix is given as list - number of rows should not be specified
            if rows != None:
                raise ValueError('Both rows and matrix as list of lists were given.')
            
            # The lists in matrix have to contain only numerical values
            for row in matrix:
                if not all([(type(e)==int or type(e)==float) for e in row]):
                    raise ValueError('Not all elements in the matrix given are numerical.')
            
            # rows have to be of the same length
            if not all([len(row) == len(matrix[0]) for row in matrix]):
                raise ValueError('Not all rows in the matrix given are of the same length.')
                
            # if nothing above - we can store the input
            self.matrix = matrix
            self.rows = len(matrix)
            self.columns = len(matrix[0])

            
    
    def __add__(self, other):
        if not (isinstance(other, nbp_m)):
            raise ValueError("Other must be of instance matrix (nbp_m).")
        
        if (len(self.matrix)!= len(other.matrix)) or (len(self.matrix[0]) != len(other.matrix[0])):
            raise ValueError('Matrices are not of the same size.')        
        m1 = self.matrix
        m2 = other.matrix
        out = []
        for row in range(len(m1)):
            out.append([m1[row][i] + m2[row][i] for i in range(len(m1[0]))])
        return nbp_m(out)
    
    def __sub__(self, other):
        if not (isinstance(other, nbp_m)):
            raise ValueError("Other must be of instance matrix (nbp_m).")        
 
        if (len(self.matrix)!= len(other.matrix)) or (len(self.matrix[0]) != len(other.matrix[0])):
            raise ValueError('Matrices are not of the same size.')
        m1 = self.matrix
        m2 = other.matrix
        out = []
        for row in range(len(m1)):
            out.append([m1[row][i] - m2[row][i] for i in range(len(m1[0]))])
        return nbp_m(out)


    
    ###################################################
    
    ### sum_matrix ###
    
    #Adds the elements of the matrices together, returns it as a new matrix
    def sum_matrix(self, lst):
        
        for other in lst:
            if not (isinstance(other, nbp_m)):
                raise ValueError("other must be a matrix (instance of nbp_m).")
            if (self.rows != other.rows or self.columns != other.columns):
                raise ValueError("The matrices are of different dimensions.")
        
        out = []
        #takes the current row and adds it together with all other using the vector equivalent of this class
        for i in range(len(self.matrix)):
            out.append(nbp_v(self.matrix[i]).sum_vec([nbp_v(other.matrix[i]) for other in lst]).vector)

        return nbp_m(out)
    
    
    ########################################################
    
    ### helping functions###

    
    def identity_matrix(dim):
        base = nbp_m([0 for i in range(dim*dim)], dim).matrix
        for i in range(dim):
            base[i][i] = 1
            
        return nbp_m(base)
    
    
    def minor(matrix, r, c):
        # taking a matrix and returning Minor M_{r,c}

        row_index = [i for i in range(len(matrix))]
        col_index = [i for i in range(len(matrix[0]))]
        row_index.remove(r-1)
        col_index.remove(c-1)

        minor = [matrix[row] for row in row_index]
        for row in range(len(minor)):
            minor[row] = [minor[row][col] for col in col_index]
        
        return nbp_m(minor)
    
    
    def is_square(self):
        return len(self.matrix) == len(self.matrix[0])
        
    def is_symmetric(self):
        return self.matrix == self.transpose().matrix

    
    ###################################################
    
    ### printing functions ###
    
    # function 'nice' is based on the Latex package
    
    def __str__(self):
        text = ''
        for row in self.matrix:
            text += str(row) + '\n'
        return '{}x{} matrix\n\n'.format(self.rows, self.columns) + text

            
    def nice(self):
        
        #The import statement is defined in the function due to reusability purposes
        #Furthermore, nice is a function purley for the user to have a nice display, and is therefore optional.
        #Having the import inside the function avoids importing a package that might not be used
        from IPython.display import display, Latex
        
        matrix_line = []
        r = self.rows
        c = self.columns

        # noting matrix in one line
        for row in self.matrix:
            matrix_line += row
        matrix_line = [round(num, 3) for num in matrix_line] # rounding so that the outcome is of normal size

        # coding the applicable string
        # using {} to control the formatting
        # using latex language and latex module
        text = ''
        text += '&'.join(['{}' for i in range(c)])

        for i in range(r-1):
            text += ' \\\ ' + '&'.join(['{}' for i in range(c)])

        gen = '$\\begin{{bmatrix}} '+text+' \end{{bmatrix}}$'
        
        gen_f = gen.format(*matrix_line)

        # printing
        display(Latex(f'{gen_f}'))
        
    ###################################################
    
    # functions for operating on matrices
    
    ### transpose function ###
    
    def transpose(self):
        
        c = self.columns
        r = self.rows
        t_m = [0 for i in range(self.rows*self.columns)]
        t_m = [t_m[x:x+r] for x in range(0, len(t_m), r)]
        
        for col in range(c):
            for row in range(r):
                t_m[col][row] = self.matrix[row][col]

        return nbp_m(t_m)

    ### scal function ###
    
    def scal(self, scalar):
        if (type(scalar) != int and type(scalar) != float):
            raise ValueError('The scalar parsed has to be a numerical value.')
        
        out = []
        for row in self.matrix:
            out.append([i*scalar for i in row])
            
        return nbp_m(out)
    
    ### Matrix multiplication ###
    def MMULT(self, other):
        #Input validation
        if not (isinstance(other, nbp_m)):
            raise ValueError('other in MMULT must be an instance of the class nbp_m.')

        if not(self.columns == other.rows):
            raise ValueError('The number of columns in the first matrix must be equal to the number of rows in the second.')
            
        res = [[0 for x in range(self.columns)] for y in range(self.rows)] 
   
        for i in range(self.rows): 
            for j in range(other.columns):
                for k in range(other.rows):
  
                    # resulted matrix
                    res[i][j] += self.matrix[i][k] * other.matrix[k][j]
                
        return nbp_m(res)
          
 
     
    ###################################################
    
    # reducing rows, find pivots, row echelon forms
    
    # class-functions/ helping functions
    
    def pivot_row(row, row_count):
        value_count = 0
        skipped = 0
        for value in row:
                if(value_count == row_count):
                    if(value != 0):
                        return value, value_count+skipped, skipped
                    else:
                        skipped += 1
                        value_count-=1
                value_count+=1
        return "Null"

    def find_pivot(matrix):

        #pivtos{row_count: [value, (position)]}
        pivots = {}
        row_count = 0
        for row in matrix:
            if(nbp_m.pivot_row(row, row_count) == "Null"):
                row_count +=1
                continue
            pivots[row_count] = [nbp_m.pivot_row(row, row_count)[0], (row_count, nbp_m.pivot_row(row, row_count)[1])]
            for i in range(nbp_m.pivot_row(row, row_count)[2]):
                row_count +=1
            row_count +=1

        return pivots
    
    def switching_rows(reduced):
        ## changes the order of the matrix if row switching is necessary, 
        ## if it is not necessary, then it leaves the rows unchanged  
        row_count = 0
        for row in reduced:
            if(nbp_m.pivot_row(row,row_count) == "Null"):
                continue
            if(nbp_m.pivot_row(row,row_count)[2] > 0):
                for r in range(row_count+1, len(reduced)):
                    if(nbp_m.pivot_row(reduced[r],0) == "Null"):
                        row_count +=1
                        continue
                    if(nbp_m.pivot_row(reduced[r],0)[1] <= nbp_m.pivot_row(row,row_count)[1]):
                        a = copy.deepcopy(reduced[row_count])
                        reduced[row_count] = reduced[r]
                        reduced[r] = a
            row_count += 1
        return reduced
    
    
    #instance functions
        
    def row_echelon_form(self):
        #row-switches if necessary
        reduced = nbp_m.switching_rows(copy.deepcopy(self.matrix))
        row_count = 0
        row = reduced[row_count]
        while(row_count < len(reduced)-1):
            if(nbp_m.pivot_row(row, row_count) == "Null"):
                row_count += 1
                continue
            pivot_value = nbp_m.pivot_row(row, row_count)[0]
            pivot_pos = nbp_m.pivot_row(row, row_count)[1]
            for i in range(1,len(reduced)):
                if(row_count+i >= len(reduced)):
                    continue
                value_under = reduced[row_count+i][pivot_pos]
                factor = (-value_under)/pivot_value
                e_count = 0
                for e in reduced[row_count+i]:
                    reduced[row_count+i][e_count] += row[e_count]*factor
                    e_count +=1
            row_count += 1
            row = reduced[row_count]
        return nbp_m(reduced)

    
        #Based on rank = number of pivot columns in a matrix's row echelon form 
    def rank(self):
        return len(nbp_m.find_pivot(self.row_echelon_form().matrix).keys())
    
    
    def determinant(self):
            
        if not(self.is_square()):
            raise ValueError("The matrix must be square to compute the determinant.")
        if (self.rows != len(nbp_m.find_pivot(self.row_echelon_form().matrix).keys())):
            return 0
        
        determinant_lst = []
        for i in nbp_m.find_pivot(self.row_echelon_form().matrix).values():
            determinant_lst.append(i[0])
        determinant = 1
        for j in determinant_lst:
            determinant *= j
        return determinant
     
        
    def inverse(self):
        if self.determinant() == 0:
            raise ValueError('The matrix is singular (determinant = 0).')        
        
        #only used for indexing -> does not need to be a copy
        matrix = self.matrix
        determinant = self.determinant()
        

        if len(matrix) == 2:
            return nbp_m([matrix[1][1], -1*matrix[0][1], -1*matrix[1][0], matrix[0][0]],2).scal(1/determinant)

        inverse = nbp_m([0 for i in range(len(matrix)*len(matrix))],len(matrix)).matrix
        
        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                minor = nbp_m.minor(matrix, i+1, j+1)
                inverse[i][j] = ((-1)**(i+1+j+1)) * minor.determinant()

        return nbp_m(inverse).transpose().scal(1/determinant)



            
    def lu(self):
        if(self.determinant() == 0):
            raise ValueError("This LU-decomposition can only be done on invertable matrices, i.e. where the determinant is non-zero")
        
        if(self.matrix != nbp_m.switching_rows(copy.deepcopy(self.matrix))):
            raise ValueError("This LU-decomposition can only be performed on matrices where row operations is not required before decomposing.")
            
        a = copy.deepcopy(self.matrix)
        dim = len(a)
        l = nbp_m([0 for i in range(dim*dim)], dim).matrix
        u = nbp_m([0 for i in range(dim*dim)], dim).matrix
        
    
        for n in range(dim):
            l[n][0] = a[n][0]
            u[0][n] = a[0][n]/a[0][0]
            u[n][n] = 1
        
        for d in range(1, dim):
            for i in range(1, dim):
                if i >= d:
                    l[i][d] = a[i][d]
                    for k in range(d):
                        l[i][d] -= l[i][k]*u[k][d]
                else:
                    l[i][d] = 0
                
                if d <= i:
                    u[d][i] = a[d][i]
                    for k in range(d):
                        u[d][i] -= l[d][k]*u[k][i]
                    u[d][i] = u[d][i]/l[d][d]
                else:
                    u[d][i] = 0
    
        return {'l':nbp_m(l), 'u':nbp_m(u)}
    


    def solve_linear(self, vec):
        if not (isinstance(vec, nbp_v)):
            raise ValueError("The input has to be a vector (of the class nbp_v).")
            
        # Solving the linear equation: Ax = b 
        # Using LU decomposition: LUx = b
        # The first step: Ly = b
        # The second step: Ux = y
        
        L = self.lu()['l'].matrix
        U = self.lu()['u'].matrix
        b = vec.vector
    
        # The first step: using forward substitution to solve Ly = b for y
        y = [0 for i in range(len(b))]
        y[0] = b[0]/L[0][0]
        for n in range(1, len(b)):
            h = b[n]
            for j in range(n):
                h -= L[n][j]*y[j]
            y[n] = h/L[n][n]


        # The second step: using backward substitution to solve Ux = y for x
        x = [0 for i in range(len(b))]
        x[-1] = y[-1]/U[-1][-1]
        for n in range(len(b)-2, -1, -1):
            h = y[n]
            for j in range(n+1, len(b)):
                h -= U[n][j]*x[j]
            x[n] = h/U[n][n]

        
        return nbp_v(x,"v")
    
    
    def gram_schmidt(self):
    
        # The matrix must be of full rank, the columns must be lineary independent.
        if (self.rank() < self.columns):
            raise ValueError("The matrix must be of full rank to compute qr using this gram_scmidt")
    
        
        #e and u are stored as lists of vectors,
        #colA is stored as a matrix,
        #r is a list of lists.
        u = []
        e = []
        colA = self.transpose()
        
        u.append(nbp_v(colA.matrix[0]))
        
        e.append(u[0].div_vec(u[0].norm))
    
        r = []
        for i in range(len(colA.matrix)):
            r.append([])
        r[0].append(nbp_v(colA.matrix[0]).dot_product(e[0]))
        r[0] = r[0] + [0]*(len(colA.matrix)-len(r[0]))
        
    
        for i in range(1, len(colA.matrix)):

            #c is a vector (nbp_v)
            c = nbp_v(colA.matrix[i])
            u_new = copy.deepcopy(c)
        
            for e_vector in e:
                u_new = u_new.sum_vec([e_vector.scalar(e_vector.dot_product(c)).scalar(-1)])

            u.append(u_new)
            e_new = u_new.div_vec(u_new.norm)
            e.append(e_new)

            for e_vector in e:
                r[i].append(c.dot_product(e_vector))
                
            r[i] = r[i] + [0]*(len(colA.matrix)-len(r[i]))
    
        q = []
        for e_vector in e:
            q.append(e_vector.vector)
                
        return {'q':nbp_m(q).transpose(), 'r':nbp_m(r).transpose()}
    
    
    def householder(self):

        # AThe matrix must be of full rank, the columns must be lineary independent.
        if (self.rank() < self.columns):
            raise ValueError("The matrix must be of full rank to compute qr using this householder")

    
        # The algorithm is from Kincaid.
    
        #dim is stored as an int,
        #q, r and A are stored as a matrix (nbp_m).
        dim = self.rows
        q = nbp_m.identity_matrix(dim)
        r = copy.deepcopy(self)
        A = self.transpose()

        for k in range(dim-1):
        
            # a1 = first column of A
            a1 = nbp_v(A.matrix[0])

            # beta 
            beta = -1*(a1.vector[0]/abs(a1.vector[0]))*a1.norm

            # e1 = the unit vector of size equal to a1
            e1 = nbp_v([1] + [0 for i in range(len(A.matrix)-1)])

            # y = a1 - beta*e1
            beta_e1 = e1.scalar(-1*beta)
            y = a1.sum_vec([beta_e1])
        
            # alpha
            alpha = (2**0.5)/y.norm
        
            # v = alpha * y
            v = y.scalar(alpha)
        
            # v*v^T matrix
            vvT = v.outer_product(nbp_v(v.vector,"v"))
            
            # U = I - vvT
            U = nbp_m.identity_matrix(a1.dimensions).sum_matrix([vvT.scal(-1)])


            # In the first iteration U does not have to be adapted to the original matrix size,
            # but the next ones have to.
            # The missing upper right part is the according part of identity matrix
            if k > 0:
                for t in range(k):
                    U.matrix.insert(0, [0 for i in range(dim)])
                for row in range(dim):
                    if len(U.matrix[row]) < dim:
                        U.matrix[row] = [0]*(dim-len(U.matrix[row])) + U.matrix[row]
                for t in range(k):
                    U.matrix[t][t] = 1

            # Updating U with the new matrix
            U = nbp_m(U.matrix)
    
            # By repetetive multiplication (U*r) we should end up with upper triangular matrix r
            r = U.MMULT(r)

            # We obtain matrix Q by multiplying obtained U_k matrices and then transposing the final product
            q = U.MMULT(q)
            
            # Taking minor of A obtained after this step
            A = nbp_m.minor(r.matrix, 1, 1)
   
    
        return {'q':q.transpose(), 'r':r}
    
    
    
    def qr(self, method = "h"):
        if(method != "h" and method != "g"):
            raise ValueError("QR decomposition can be acchieved with the Gram Schmidt- or Householder methods, please select method = g or method = h.")
    
        if method == 'g':
            return {'q': self.gram_schmidt()["q"], 'r': self.gram_schmidt()["r"]}
        
        return {'q': self.householder()["q"], 'r': self.householder()["r"]}
    
    
    
    def qr_alg(self, iterations=100, method = "h"):
        
        ## We are also validating method here, so that no variables will be stored before qr is called. 
        if(method != "h" and method != "g"):
            raise ValueError("QR decomposition can be acchieved with the Gram Schmidt- or Householder methods, please select method = g or method = h.")
            
        if (self.rank() < self.columns):
            raise ValueError("The matrix must be of full rank to compute qr using this algorithm.")
        
        values = copy.deepcopy(self)
        vectors = copy.deepcopy(self)
  
        for i in range(iterations):

            # Storing values.qr(method) in v to not compute twice in order to improve performance (significantly when iterations are 100+) 
            v = values.qr(method)
            q_val = v['q']
            r_val = v['r']
            q_vec = vectors.qr(method)['q']
            
            values = r_val.MMULT(q_val)
            vectors = self.MMULT(q_vec)
        
        return {'m':values, 'eig':vectors.qr()['q']}

    
    
    def eigen(self, method = "h"):
        if not self.is_square():
            raise ValueError("Can only compute eigenvalues of a square matrix")
        
        if not self.is_symmetric():
            raise ValueError("this function can only compute eigenvalues for symmetric matrices")
    
        eigen_values = [round(self.qr_alg()['m'].matrix[i][i],3) for i in range(self.rows)]
        eigen_vectors = self.qr_alg()['eig'].transpose().matrix
        for k in range(len(eigen_vectors)):
            eigen_vectors[k] = [round(x,3) for x in eigen_vectors[k]]
    
        return {'values':nbp_v(eigen_values), 'vectors':nbp_m(eigen_vectors)}
    
    
    def diagonalize(self, method = "h"):
        if not (self.is_symmetric()):
            raise ValueError("Diagonalize can only be done for symmetric matrices, since that is a requirement for computing eigenvalues in this library")
        
        # The output is PDP^-1
        # D = matrix with eigenvalues
        # P = matrix containing of corresponding eigenvalues
        # P-1 = the transposed of matrix P
    
        D = nbp_m.identity_matrix(self.rows)
    
        for i in range(self.rows):
            D.matrix[i][i] = self.eigen(method)["values"].vector[i]
        

        
        P = self.eigen(method)["vectors"].transpose()

    
        return {'D':D, 'P':P, 'P-1':P.inverse()}


        

In [35]:
import numpy as np


#Declaring variables numpy
A = np.matrix([[2,6,9],[6,8,5],[9,5,8]])
V = np.array([1, 1, 1])
V2 = np.array([1, 2, 3])


#Declaring variables nbp
a = nbp_m([2, 6, 9, 6, 8, 5, 9, 5, 8], 3)
v = nbp_v([1,1,1],"v")
v2 = nbp_v([1,2,3])


print("Comparing vectors:")
print("\nComparing dot product:")
print("In NumPy: ")
print(np.dot(V,V2))
print("In nbp: ")
print(v.dot_product(v2))

print("\nComparing outer product:")
print("In NumPy: ")
print(np.outer(V,V2))
print("In nbp: ")
v.outer_product(v2).nice()


print("\n\nComparing matrices to numpy:")
print("\nComparing transpose:")
print("In NumPy: ")
print(A.transpose())
print("In nbp:")
a.transpose().nice()

print("\nComparing MMULT:")
print("In NumPy: ")
print(np.matmul(A,A))
print("In nbp:")
a.MMULT(a).nice()

print("\nComparing inverse:")
print("In NumPy: ")
print(np.linalg.inv(A))
print("In nbp:")
a.inverse().nice()

print("\nComparing determinant:")
print("In NumPy: ")
print(np.linalg.det(A))
print("In nbp:")
print(a.determinant())

print("\nComparing rank: ")
print("In NumPy: ")
print(np.linalg.matrix_rank(A))
print("In nbp: ")
print(a.rank())

print("\nComparing eigen-vlaues and vectors: ")
print("In NumPy: ")
print(np.linalg.eig(A))
print("Eigenvalues in nbp:")
a.eigen()["values"].nice()
print("Eigenvectors in nbp: ")
a.eigen()["vectors"].nice()

print("\nComparing solve linear: ")
print("iIn NumPy: ")
print(np.linalg.solve(A,V))
print("In nbp: ")
a.solve_linear(v).nice()








Comparing vectors:

Comparing dot product:
In NumPy: 
6
In nbp: 
6

Comparing outer product:
In NumPy: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
In nbp: 


<IPython.core.display.Latex object>



Comparing matrices to numpy:

Comparing transpose:
In NumPy: 
[[2 6 9]
 [6 8 5]
 [9 5 8]]
In nbp:


<IPython.core.display.Latex object>


Comparing MMULT:
In NumPy: 
[[121 105 120]
 [105 125 134]
 [120 134 170]]
In nbp:


<IPython.core.display.Latex object>


Comparing inverse:
In NumPy: 
[[-0.12264151  0.00943396  0.13207547]
 [ 0.00943396  0.20440252 -0.13836478]
 [ 0.13207547 -0.13836478  0.06289308]]
In nbp:


<IPython.core.display.Latex object>


Comparing determinant:
In NumPy: 
-318.0
In nbp:
-318.0000000000001

Comparing rank: 
In NumPy: 
3
In nbp: 
3

Comparing eigen-vlaues and vectors: 
In NumPy: 
(array([19.521911  , -4.86807641,  3.34616541]), matrix([[ 0.52261231,  0.83769062,  0.15859002],
        [ 0.55354111, -0.19191425, -0.81040802],
        [ 0.64843552, -0.5113153 ,  0.56399295]]))
Eigenvalues in nbp:


<IPython.core.display.Latex object>

Eigenvectors in nbp: 


<IPython.core.display.Latex object>


Comparing solve linear: 
iIn NumPy: 
[0.01886792 0.0754717  0.05660377]
In nbp: 


<IPython.core.display.Latex object>